backend:
    name: git-gateway
    branch: master

media_folder: "../static/images/uploads"
public_folder: "../images/uploads"

collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
  folder: "_posts"
