backend:
    name: git-gateway
    branch: master

media_folder: "../static/images/uploads"
public_folder: "../images/uploads"

collections:
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    folder: "_posts"
